language: r
sudo: false
cache: packages
dist: trusty

after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change
